{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# default_exp dash"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Dash\n",
    "\n",
    "> Plotly Dash application to visualize and recommendations\n",
    "\n",
    "https://plot.ly/dash/"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#hide\n",
    "from nbdev.export import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#export\n",
    "import dash\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html\n",
    "from dash.dependencies import Input, Output\n",
    "\n",
    "from functools import lru_cache\n",
    "from pathlib import Path\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import requests\n",
    "\n",
    "from word2vec_recommender.core import *\n",
    "from word2vec_recommender.recommender import KnnRecommender\n",
    "from word2vec_recommender.tmdb import load_api_key, TmdbApi, MovieData"
   ]
  },
  {
   "cell_type": "markdown",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Load data frames"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#export\n",
    "movies_df = pd.read_csv(\"./data/ml-latest-small/movies.csv\")\n",
    "links_df = pd.read_csv(\"./data/ml-latest-small/links.csv\")"
   ]
  },
  {
   "cell_type": "markdown",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Load Tmdb Api"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#export\n",
    "movielens_to_tmdb_lookup = { int(movie_id):int(tmdb_id)  for movie_id, tmdb_id in links_df.set_index(\"movieId\")[\"tmdbId\"].to_dict().items() if movie_id > 0 and tmdb_id > 0 }\n",
    "api = TmdbApi(api_key=load_api_key(), movielens_to_tmdb_lookup=movielens_to_tmdb_lookup)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#export\n",
    "with open(Path(\"./data/out/embeddings.pkl\"), \"rb\") as f:\n",
    "    embeddings = np.load(f)\n",
    "with open(Path(\"./data/out/words_index.pkl\"), \"rb\") as f:\n",
    "    word_indexes = np.load(f)\n",
    "\n",
    "movie_id_to_index_lookup = {int(movie_id):idx for idx, movie_id in enumerate(word_indexes)}\n",
    "\n",
    "knn_recommender = KnnRecommender(\n",
    "    word_indexes=word_indexes, \n",
    "    embeddings=embeddings)\n",
    "\n",
    "knn_recommender.fit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#export\n",
    "external_stylesheets = []\n",
    "\n",
    "app = dash.Dash(__name__, \n",
    "    external_stylesheets=external_stylesheets)\n",
    "\n",
    "app.layout = html.Div(children=[\n",
    "    html.H1(children='MovieLens Recommender based on Word2Vec'),\n",
    "\n",
    "    html.Div(children='''\n",
    "        Dash: A web application framework for Python.\n",
    "    '''),\n",
    "    dcc.Dropdown(\n",
    "        id=\"movie-id\",\n",
    "        options=movies_df[[\"title\", \"movieId\"]].apply(lambda r:  {\"value\": r[\"movieId\"], \"label\": r[\"title\"]} ,axis=1).tolist(),\n",
    "    ),\n",
    "    html.Div(id=\"selected-movie-id\", children=\"\")\n",
    "])\n",
    "\n",
    "def movie_card(movie: MovieData, seed: bool = False) -> html.Div:\n",
    "    description = f\"{movie.title} (id={movie.movie_id}, tmdb_id={movie.tmdb_id})\"\n",
    "    return html.Div(children=[\n",
    "        html.H2(description) if seed else html.H3(description),\n",
    "        html.Img(src=movie.image_url)\n",
    "    ])\n",
    "\n",
    "@app.callback(\n",
    "    Output(component_id='selected-movie-id', component_property='children'),\n",
    "    [Input(component_id='movie-id', component_property='value')]\n",
    ")\n",
    "def update_output_div(movie_id) -> html.Div:\n",
    "    if not movie_id:\n",
    "        return html.Div(children=\"No movie selected\")\n",
    "    print(movie_id)\n",
    "    movie = api.fetch_movie_data_by_movielens_id(int(movie_id))\n",
    "    movie_index = movie_id_to_index_lookup.get(int(movie_id))\n",
    "    movie_recs = knn_recommender.recommend_by_index(movie_index)\n",
    "    movies = [ api.fetch_movie_data_by_movielens_id(rec.movie_id) for rec in movie_recs ]\n",
    "    return html.Div(children=[\n",
    "        movie_card(movie, seed=True),\n",
    "        html.Div(children=[\n",
    "            html.H2(\"Recommendations\"),\n",
    "            *[movie_card(m) for m in movies]\n",
    "            ])\n",
    "        ]) "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#export\n",
    "def start_dash(debug: bool = True):\n",
    "    app.run_server(debug=debug, port=9998)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      ".7/site-packages/dash/dash.py\", line 1337, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-52-4195976523c6>\", line 37, in update_output_div\n",
      "    movie_recs = knn_recommender.recommend_by_index(movie_index)\n",
      "  File \"/Users/felipe.gasparini/Projects/udacity/ml-engineer/udacity_mle_word2vec_recommender/word2vec_recommender/recommender.py\", line 51, in recommend_by_index\n",
      "    distances_array, indexes_array = self.nn_model.kneighbors([embedding])\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/sklearn/neighbors/base.py\", line 402, in kneighbors\n",
      "    X = check_array(X, accept_sparse='csr')\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 539, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 4. Estimator expected <= 2.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/dash/dash.py\", line 1457, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/dash/dash.py\", line 1337, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-52-4195976523c6>\", line 37, in update_output_div\n",
      "    movie_recs = knn_recommender.recommend_by_index(movie_index)\n",
      "  File \"/Users/felipe.gasparini/Projects/udacity/ml-engineer/udacity_mle_word2vec_recommender/word2vec_recommender/recommender.py\", line 51, in recommend_by_index\n",
      "    distances_array, indexes_array = self.nn_model.kneighbors([embedding])\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/sklearn/neighbors/base.py\", line 402, in kneighbors\n",
      "    X = check_array(X, accept_sparse='csr')\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 539, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 4. Estimator expected <= 2.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/dash/dash.py\", line 1457, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/dash/dash.py\", line 1337, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-52-4195976523c6>\", line 37, in update_output_div\n",
      "    movie_recs = knn_recommender.recommend_by_index(movie_index)\n",
      "  File \"/Users/felipe.gasparini/Projects/udacity/ml-engineer/udacity_mle_word2vec_recommender/word2vec_recommender/recommender.py\", line 51, in recommend_by_index\n",
      "    distances_array, indexes_array = self.nn_model.kneighbors([embedding])\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/sklearn/neighbors/base.py\", line 402, in kneighbors\n",
      "    X = check_array(X, accept_sparse='csr')\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 539, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 4. Estimator expected <= 2.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/dash/dash.py\", line 1457, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/dash/dash.py\", line 1337, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-52-4195976523c6>\", line 37, in update_output_div\n",
      "    movie_recs = knn_recommender.recommend_by_index(movie_index)\n",
      "  File \"/Users/felipe.gasparini/Projects/udacity/ml-engineer/udacity_mle_word2vec_recommender/word2vec_recommender/recommender.py\", line 51, in recommend_by_index\n",
      "    distances_array, indexes_array = self.nn_model.kneighbors([embedding])\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/sklearn/neighbors/base.py\", line 402, in kneighbors\n",
      "    X = check_array(X, accept_sparse='csr')\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 539, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 4. Estimator expected <= 2.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/dash/dash.py\", line 1457, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/dash/dash.py\", line 1337, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-52-4195976523c6>\", line 37, in update_output_div\n",
      "    movie_recs = knn_recommender.recommend_by_index(movie_index)\n",
      "  File \"/Users/felipe.gasparini/Projects/udacity/ml-engineer/udacity_mle_word2vec_recommender/word2vec_recommender/recommender.py\", line 51, in recommend_by_index\n",
      "    distances_array, indexes_array = self.nn_model.kneighbors([embedding])\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/sklearn/neighbors/base.py\", line 402, in kneighbors\n",
      "    X = check_array(X, accept_sparse='csr')\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 539, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 4. Estimator expected <= 2.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/dash/dash.py\", line 1457, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/dash/dash.py\", line 1337, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-52-4195976523c6>\", line 37, in update_output_div\n",
      "    movie_recs = knn_recommender.recommend_by_index(movie_index)\n",
      "  File \"/Users/felipe.gasparini/Projects/udacity/ml-engineer/udacity_mle_word2vec_recommender/word2vec_recommender/recommender.py\", line 51, in recommend_by_index\n",
      "    distances_array, indexes_array = self.nn_model.kneighbors([embedding])\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/sklearn/neighbors/base.py\", line 402, in kneighbors\n",
      "    X = check_array(X, accept_sparse='csr')\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 539, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 4. Estimator expected <= 2.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/dash/dash.py\", line 1457, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/dash/dash.py\", line 1337, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-52-4195976523c6>\", line 37, in update_output_div\n",
      "    movie_recs = knn_recommender.recommend_by_index(movie_index)\n",
      "  File \"/Users/felipe.gasparini/Projects/udacity/ml-engineer/udacity_mle_word2vec_recommender/word2vec_recommender/recommender.py\", line 51, in recommend_by_index\n",
      "    distances_array, indexes_array = self.nn_model.kneighbors([embedding])\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/sklearn/neighbors/base.py\", line 402, in kneighbors\n",
      "    X = check_array(X, accept_sparse='csr')\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 539, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 4. Estimator expected <= 2.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/dash/dash.py\", line 1457, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/dash/dash.py\", line 1337, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-52-4195976523c6>\", line 37, in update_output_div\n",
      "    movie_recs = knn_recommender.recommend_by_index(movie_index)\n",
      "  File \"/Users/felipe.gasparini/Projects/udacity/ml-engineer/udacity_mle_word2vec_recommender/word2vec_recommender/recommender.py\", line 51, in recommend_by_index\n",
      "    distances_array, indexes_array = self.nn_model.kneighbors([embedding])\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/sklearn/neighbors/base.py\", line 402, in kneighbors\n",
      "    X = check_array(X, accept_sparse='csr')\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 539, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 4. Estimator expected <= 2.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/dash/dash.py\", line 1457, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/dash/dash.py\", line 1337, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"<ipython-input-52-4195976523c6>\", line 37, in update_output_div\n",
      "    movie_recs = knn_recommender.recommend_by_index(movie_index)\n",
      "  File \"/Users/felipe.gasparini/Projects/udacity/ml-engineer/udacity_mle_word2vec_recommender/word2vec_recommender/recommender.py\", line 51, in recommend_by_index\n",
      "    distances_array, indexes_array = self.nn_model.kneighbors([embedding])\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/sklearn/neighbors/base.py\", line 402, in kneighbors\n",
      "    X = check_array(X, accept_sparse='csr')\n",
      "  File \"/usr/local/Caskroom/miniconda/base/envs/udacity_project/lib/python3.7/site-packages/sklearn/utils/validation.py\", line 539, in check_array\n",
      "    % (array.ndim, estimator_name))\n",
      "ValueError: Found array with dim 4. Estimator expected <= 2.\n",
      "127.0.0.1 - - [19/Dec/2019 23:32:12] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "135\n",
      ">tmdb_movie_id 9091\n",
      ">tmdb_movie_id 12121\n",
      ">tmdb_movie_id 11525\n",
      ">tmdb_movie_id 11858\n",
      ">tmdb_movie_id 19042\n",
      ">tmdb_movie_id 10535\n",
      "127.0.0.1 - - [19/Dec/2019 23:32:40] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      ">tmdb_movie_id 12110\n"
     ]
    }
   ],
   "source": [
    "#hide   \n",
    "start_dash(False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
